### get all products
GET http://localhost:5000/api/products HTTP/1.1

### 

GET http://localhost:5000/api/products/602bf8793a57401e9732c021 HTTP/1.1

###

POST http://localhost:5000/api/users/login HTTP/1.1
Content-Type: application/json

{
    "email": "admin@gmail.com",
    "password": "123456"
}

### 
POST http://localhost:5000/api/users HTTP/1.1
Content-Type: application/json

{
    "name": "Reach",
    "email": "reach@gmail.com",
    "password": "123456"
}

###
GET http://localhost:5000/api/users/profile HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwMmJmYzYzZGYyNmFmMjMyZGY3NTQ5MSIsImlhdCI6MTYxMzUwMzI5NSwiZXhwIjoxNjE2MDk1Mjk1fQ.u6aTiz-mzpeV6NeTfILn885hl_E5Wh-2CuuqurVJV5E

### update profile 
PUT http://localhost:5000/api/users/profile HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwMmJmYzYzZGYyNmFmMjMyZGY3NTQ5MSIsImlhdCI6MTYxMzUwMzI5NSwiZXhwIjoxNjE2MDk1Mjk1fQ.u6aTiz-mzpeV6NeTfILn885hl_E5Wh-2CuuqurVJV5E
Content-Type: application/json

{
    "name": "Admin User"
}
