### get all products
GET http://localhost:5000/api/products HTTP/1.1

### 

GET http://localhost:5000/api/products/602bf4c68c0ca81a5293d573 HTTP/1.1

###

POST http://localhost:5000/api/users/login HTTP/1.1
content-type: application/json

{
    "email": "samreachyan@gmail.com",
    "password": "123456"
}