### get all products
GET http://localhost:5000/api/products HTTP/1.1

### 

GET http://localhost:5000/api/products/602d3f78a31cdb1c8df33eb2 HTTP/1.1

###

POST http://localhost:5000/api/users/login HTTP/1.1
Content-Type: application/json

{
    "email": "admin@gmail.com",
    "password": "123456"
}

### 
POST http://localhost:5000/api/users/login HTTP/1.1
Content-Type: application/json

{
    "email": "samreachyan@gmail.com",
    "password": "123456"
}

### 
POST http://localhost:5000/api/users HTTP/1.1
Content-Type: application/json

{
    "name": "Reach",
    "email": "reach@gmail.com",
    "password": "123456"
}

###
GET http://localhost:5000/api/users/profile HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwMmJmYzYzZGYyNmFmMjMyZGY3NTQ5MSIsImlhdCI6MTYxMzUwMzI5NSwiZXhwIjoxNjE2MDk1Mjk1fQ.u6aTiz-mzpeV6NeTfILn885hl_E5Wh-2CuuqurVJV5E

### update profile 
PUT http://localhost:5000/api/users/profile HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwMmJmYzYzZGYyNmFmMjMyZGY3NTQ5MSIsImlhdCI6MTYxMzUwMzI5NSwiZXhwIjoxNjE2MDk1Mjk1fQ.u6aTiz-mzpeV6NeTfILn885hl_E5Wh-2CuuqurVJV5E
Content-Type: application/json

{
    "name": "Admin User"
}

### View order by id
GET http://localhost:5000/api/orders/602cd5e1dd1c4c3d330d559e HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwMmNkNTY3MWMyZWI2M2NkNDU3ZDhjZCIsImlhdCI6MTYxMzU1MTQ3MywiZXhwIjoxNjE2MTQzNDczfQ.x0rL9i2oFrTI7j7dr8uVL2DhDp3-YFAakw3cQTOrfWw


### get my orders 
GET http://localhost:5000/api/orders/myorders HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwMmQzZjc3YTMxY2RiMWM4ZGYzM2ViMCIsImlhdCI6MTYxMzU4NTYzMCwiZXhwIjoxNjE2MTc3NjMwfQ.9KiEc1-t1Qm5ckH4mqQauiUPkAen3oXKopigjXcHwSQ

### get all users / admin
GET http://localhost:5000/api/users HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwMmQzZjc3YTMxY2RiMWM4ZGYzM2VhZiIsImlhdCI6MTYxMzYyNDA1MiwiZXhwIjoxNjE2MjE2MDUyfQ.uJSzKoRMddlErurHGXIJ5BjAylry9-q2_HGj7Eh2U9U

### get user by id
GET http://localhost:5000/api/users/602d3f77a31cdb1c8df33eb1 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwMmQzZjc3YTMxY2RiMWM4ZGYzM2VhZiIsImlhdCI6MTYxMzY2ODYwMiwiZXhwIjoxNjE2MjYwNjAyfQ.xFJmHIBGs8IsFHM64c3LMqXiJF3TQMtSggJP_4g4N7M

### create product by admin
POST http://localhost:5000/api/products HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwMmQzZjc3YTMxY2RiMWM4ZGYzM2VhZiIsImlhdCI6MTYxMzY2ODYwMiwiZXhwIjoxNjE2MjYwNjAyfQ.xFJmHIBGs8IsFHM64c3LMqXiJF3TQMtSggJP_4g4N7M


### Review product id
POST http://localhost:5000/api/products/602d3f78a31cdb1c8df33eb2/reviews
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwMmQzZjc3YTMxY2RiMWM4ZGYzM2ViMCIsImlhdCI6MTYxMzY3NzU1MiwiZXhwIjoxNjE2MjY5NTUyfQ.N2Y3ZY9-kvfUQl8EUJU4CnCq4dgpGb_hj8dxp6i55Ns

{
    "rating": 5,
    "comment": "This product are nice. Test rating from samreach"
}